name: CI-CD

on:
  push:
    branches:
      - master
      - main
    tags:
      - v\d+\.\d+\.\d+


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -al /home/runner/work/
      # - run: exit 2


  set_up_docker:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # checkout will be done by buildkit

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push:
    needs: set_up_docker
    runs-on: ubuntu-latest
    steps:
      - id: tag_name
        run: |
          if [[ ${GITHUB_REF%/*} = "refs/tags" ]]; then
            echo "::set-output name=value::${GITHUB_REF##*/}"
          else
            echo "::set-output name=value::latest"
          fi

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE }}:${{ steps.tag_name.outputs.value }}


  deployment:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_REF##*/}
